apiVersion: v1
data:
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: 20-kubernetes/08-vault/server-profiles/pingfederate
  SERVER_PROFILE_URL: https://github.com/devopslondon2021/pingidentity-devops-getting-started.git
  PING_IDENTITY_DEVOPS_USER: hagarwal9200@gmail.com
  PING_IDENTITY_DEVOPS_KEY: 9a93b539-22c5-09a8-960c-ac9d2b79e1d4
  # The K8S_AUTH_ROLE value must match the kubernetes role for this application/product.
  # Example: ping-cloud-devops-eks-junk-dev-pingfederate
  K8S_AUTH_ROLE: default-dev-pingfederate
  # The VAULT API base address (with scheme) that is used to communicate with vault. 
  # Example: https://172.20.36.4:8200
  VAULT_ADDR: https://vault:8200
kind: ConfigMap
metadata:
  labels:
    role: pingfederate
  name: pingfederate-environment-variables